- hosts: webservers
  become: yes
  become_method: sudo
  remote_user: ubuntu
  gather_facts: False
  vars:
    SampleMsg: "This is an Apache page"

  tasks:
    - include: 'roles/tasks/01-install-apache.yml'
    - include: 'roles/tasks/02-deploy-website-files.yml'

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted