- hosts: webservers
  become: yes
  become_method: sudo
  remote_user: ubuntu
  gather_facts: False
  vars:
    SampleMsg: "Welcome to this demo"

  tasks:
    - include: 'roles/tasks/01-install-nginx.yml'
    - include: 'roles/tasks/02-deploy-website-files.yml'