- hosts: webservers
  become: yes
  become_method: sudo
  remote_user: ubuntu
  gather_facts: False
  vars:
    SampleMsg: "Welcome to this demo"

  tasks:
    - include: 'tasks/nginx-install.yml'
    - include: 'tasks/copy-file.yml'